import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <SidebarProvider>
            <div className="md:hidden">
              <AppSidebar />
            </div>
            <div className="w-full h-fit border-b-2 p-3   flex  justify-between items-center">
              <div className="font-mono md:text-2xl  text-[15px]  dark:text-purple-500 font-extrabold">
                &lt;/Saksham&gt;
              </div>
              <Navbar />
            </div>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
